R code for asymptotic variance of MDPDE and MLE

```{r}

library(latex2exp)
library(ggplot2)
library(mev)
library(matlib)
library(MASS)

options(scipen = 999)
```


Score functions of the GEV

```{r}

# for the location parameter

S_mu <- Vectorize(function(x, mu, sigma, xi) {
  
  z <- (x - mu) / sigma
  term <- 1 + xi * z
  
  if (abs(xi) >= 0.01){
  result <- (1 / sigma) * (term)^(-1) * (xi + 1 - term^(-1 / xi))
  }
  
  if (abs(xi) < 0.01){
  result <- (1 / sigma) * (1-exp(-z))
  }

  return(result)
}, vectorize.args = c("x", "mu", "sigma", "xi"))

# for the scale parameter

S_sigma <- Vectorize(function(x, mu, sigma, xi) {

  z <- (x - mu) / sigma
  term <- 1 + xi * z
  
  if (abs(xi) >= 0.01){
  result <- -1 / sigma + (x - mu) / sigma^2 * (term)^(-1) * ((xi + 1) - term^(-1 / xi))
  }
  
  if (abs(xi) < 0.01){
  result <- (1 / sigma) *(-1 + z*(1-exp(-z)))
  }
  
  return(result)
}, vectorize.args = c("x", "mu", "sigma", "xi"))

# for the shape parameter

S_xi <- Vectorize(function(x, mu, sigma, xi) {

  z <- (x - mu) / sigma
  term <- 1 + xi * z
  
  if (abs(xi) >= 0.01){
    
    part1 <- (1/xi^2)*log(term)*(1-term^(-1/xi))
    
    part2 <- (1/xi)*z*term^(-1)*(term^(-1/xi)-1)
    
    part3 <- -z*term^(-1)
    
    result <- part1+part2+part3
    
  }
  
  if (abs(xi) < 0.01){
    
    result <- (1/2)*z^2*(1-exp(-z))-z
    
  }
  return(result)
}, vectorize.args = c("x", "mu", "sigma", "xi"))

S <- Vectorize(function(x, mu, sigma, xi) {
  c(S_mu(x, mu, sigma, xi),S_sigma(x, mu, sigma, xi),S_xi(x, mu, sigma, xi))
}, vectorize.args = c("x", "mu", "sigma", "xi"))
```

```{r}
xi <- seq(-0.4,0.4,0.01)
y <- S_sigma(1,0,1,xi)

plot(xi,y)
```

Quantities involved in the asymptotic variance

```{r}

x <- 1
mu <- 0
sigma <- 1
xi <- 0
alpha <- 0.1


### J_\alpha

function_J_alpha <- function(x, mu, sigma, xi, alpha){
  s1 <- S_mu(x, mu, sigma, xi)
  s2 <- S_sigma(x, mu, sigma, xi)
  s3 <- S_xi(x, mu, sigma, xi)
  d  <- dgev(x = x, loc = mu, scale = sigma, shape = xi)^(1 + alpha)
  
  M <- c(s1, s2, s3) %*% t(c(s1, s2, s3)) * d
  return(M)
}

x <- seq(-5,100)
test <- sapply(x, function(x)
    {
    function_J_alpha(x,mu = mu,
                                          sigma = sigma,
                                          xi = -0.05,
                                          alpha = alpha)
    }
    )[9,]
plot(x,test)

J_alpha <- function(mu, sigma, xi, alpha){
  
  J <- matrix(nrow = 3, ncol = 3)
  
  if (xi >= 0.01){
    lower <- mu - sigma/xi+0.001
    upper <- mu+100
  } else if (abs(xi) < 0.01){
    lower <- mu-100
    upper <- mu+100
  } else {
    lower <- mu-100
    upper <- mu + sigma/abs(xi)-0.001
  }
  
  for (i in 1:3){
    for (j in 1:3){
      integrand_ij <- function(x) {
        sapply(x, function(xx) {
          M <- function_J_alpha(xx, mu, sigma, xi, alpha)
          M[i, j]
  })
}
      res <- tryCatch(
      integrate(integrand_ij, lower, upper, stop.on.error = T),
      error = function(e) list(value = NA, abs.error = NA)
    )
    J[i, j] <- res$value
    }
  }
  
  return(J)
}


### U_\alpha

function_U_alpha <- function(x, mu, sigma, xi, alpha){
  s1 <- S_mu(x, mu, sigma, xi)
  s2 <- S_sigma(x, mu, sigma, xi)
  s3 <- S_xi(x, mu, sigma, xi)
  d  <- dgev(x = x, loc = mu, scale = sigma, shape = xi)^(1 + alpha)
  
  # for scalar x returns length-3 vector
  M <- c(s1, s2, s3) * d
  return(M)
}

U_alpha <- function(mu, sigma, xi, alpha){
  
  U <- numeric(3)
  
  if (xi >= 0.01){
    lower <- mu - sigma/xi+0.001
    upper <- mu+100
  } else if (abs(xi) < 0.01){
    lower <- mu-100
    upper <- mu+100
  } else {
    lower <- mu-100
    upper <- mu - sigma/xi-0.001
  }
  
  for (i in 1:3){
    integrand_i <- function(x) {
      sapply(x, function(xx) {
        M <- function_U_alpha(xx, mu, sigma, xi, alpha)
        M[i]  
      })
    }
    res <- tryCatch(
      integrate(integrand_i, lower, upper, stop.on.error = FALSE),
      error = function(e) list(value = NA, abs.error = NA)
    )
    U[i] <- res$value
  }
  
  return(U)
}


### K_\alpha

K_alpha <- function(mu, sigma, xi, alpha){
  return(J_alpha(mu, sigma, xi, 2*alpha)-U_alpha(mu, sigma, xi, alpha) %*% t(U_alpha(mu, sigma, xi, alpha)))
}

```

Asymptotic variance MDPDE

```{r}

asymptotic_variance_mdpde <- function(mu, sigma, xi, alpha){

  J <- J_alpha(mu, sigma, xi, alpha)
  
  inv_J_alpha <- tryCatch(
    ginv(J),
    error=function(e) {
      matrix(NA, nrow=nrow(J), ncol=ncol(J))
    }
  )
  
  return(inv_J_alpha %*% K_alpha(mu, sigma, xi, alpha) %*% inv_J_alpha)
}




asymptotic_variance_mdpde_componentwise <- function(mu, sigma, xi, alpha,coord=c(i,j)){

  asymptotic_variance_mdpde <- asymptotic_variance_mdpde(mu, sigma, xi, alpha)
  
  return(asymptotic_variance_mdpde[coord[1],coord[2]])
}




xi_vals <- seq(-0.05,0.05,0.01)


test <- sapply(xi_vals, function(xi)
    {
    print(xi)
    asymptotic_variance_mdpde_componentwise(mu = mu,
                                          sigma = sigma,
                                          xi = xi,
                                          alpha = alpha,
                                          coord=c(3,3))
    }
    )
```

Plot asymptotic variances

Location/scale parameters

```{r}

alphas <- c(0, 0.1, 0.3, 0.5, 1)

mu <- 0
sigma <- 1

plot_data_loc <- data.frame()
plot_data_scale <- data.frame() 

for (alpha in alphas) {
  print(alpha)
  xi_min <- -(1 + alpha) / (2 + alpha)
  
  xi_vals <- seq(round(xi_min+0.01,2), 1, 0.01)
  
  y_loc <- sapply(xi_vals, function(xi)
    {
    print(xi)
    asymptotic_variance_mdpde_componentwise(mu = mu,
                                          sigma = sigma,
                                          xi = xi,
                                          alpha = alpha,
                                          coord=c(1,1))
    }
    )
  df_loc <- data.frame(x = xi_vals, y = y_loc, alpha = as.factor(alpha))
  plot_data_loc <- rbind(plot_data_loc, df_loc)
  
  
  
  
  y_scale <- sapply(xi_vals, function(xi)
    {
    print(xi)
    asymptotic_variance_mdpde_componentwise(mu = mu,
                                          sigma = sigma,
                                          xi = xi,
                                          alpha = alpha,
                                          coord=c(2,2))
    }
    )
  df_scale <- data.frame(x = xi_vals, y = y_scale, alpha = as.factor(alpha))
  plot_data_scale <- rbind(plot_data_scale, df_scale)
}

```

```{r}
save(plot_data_loc,file=paste0("C:/Users/Nathan Huet/github_repos/robustGEV/simulation/generated_datasets/df_asymptotic_variance_mu.RData"))

save(plot_data_scale,file=paste0("C:/Users/Nathan Huet/github_repos/robustGEV/simulation/generated_datasets/df_asymptotic_variance_sigma.RData"))


plot_data_filtered_loc <- plot_data_loc[-c(683,689),]

plot_data_loc_clean <- na.omit(plot_data_filtered_loc)

plot_data_filtered_scale <- plot_data_scale[-c(683,689),]

plot_data_scale_clean <- na.omit(plot_data_filtered_scale)
```

Plot asymptotic variance location 

```{r}
dev.off()
plot_asymptotic_variance_mu <- ggplot(plot_data_loc_clean, aes(x = x, y = y, color = alpha)) +
  geom_line(size = 1.2) +
  theme_minimal() +
    scale_colour_viridis_d(option = "plasma",
                           name = expression(~~~~alpha))+
  labs(
    x = TeX("$\\xi$"),
    y = "Variance"
  )+
  # scale_x_continuous(
  #   breaks = list_quantile,
  #   labels = p
  # ) +
  theme(legend.position ="none",
        legend.title=element_text(size=26,face="bold"),
        legend.text =element_text(size=24))+
  theme(
    axis.title = element_text(size = 24),   
    axis.text = element_text(size = 18)
  )
plot_asymptotic_variance_mu
```

```{r}
ggsave(plot = plot_asymptotic_variance_mu,
       filename = paste0("C:/Users/Nathan Huet/github_repos/robustGEV/simulation/figures/asymptotic_variance_loc.png"),
       width = 1760 / 180,
       height = 1060 / 180,
       dpi = 180,
       units = "in")
```


Plot asymptotic variance scale 

```{r}
dev.off()
plot_asymptotic_variance_sigma <- ggplot(plot_data_scale_clean, aes(x = x, y = y, color = alpha)) +
  geom_line(size = 1.2) +
  theme_minimal() +
    scale_colour_viridis_d(option = "plasma",
                           name = expression(~~~~alpha))+
  labs(
    x = TeX("$\\xi$"),
    y = "Variance"
  )+
  # scale_x_continuous(
  #   breaks = list_quantile,
  #   labels = p
  # ) +
  theme(legend.position ="none",
        legend.title=element_text(size=26,face="bold"),
        legend.text =element_text(size=24))+
  theme(
    axis.title = element_text(size = 24),   
    axis.text = element_text(size = 18)
  )
plot_asymptotic_variance_sigma
```

```{r}
ggsave(plot = plot_asymptotic_variance_sigma,
       filename = paste0("C:/Users/Nathan Huet/github_repos/robustGEV/simulation/figures/asymptotic_variance_sigma.png"),
       width = 1760 / 180,
       height = 1060 / 180,
       dpi = 180,
       units = "in")
```


Shape parameters

```{r}

alphas <- c(0, 0.1, 0.3, 0.5, 1)

mu <- 0
sigma <- 1

plot_data <- data.frame()

for (alpha in alphas) {
  print(alpha)
  xi_min <- -(1 + alpha) / (2 + alpha)
  
  xi_vals <- seq(round(xi_min+0.01,2), 1, 0.01)
  
  y <- sapply(xi_vals, function(xi)
    {
    print(xi)
    asymptotic_variance_mdpde_componentwise(mu = mu,
                                          sigma = sigma,
                                          xi = xi,
                                          alpha = alpha,
                                          coord=c(3,3))
    }
    )
  df <- data.frame(x = xi_vals, y = y, alpha = as.factor(alpha))
  plot_data <- rbind(plot_data, df)
}

```

```{r}
save(plot_data,file=paste0("C:/Users/huetn/Documents/github_repos/robustGEV/simulation/generated_datasets/df_asymptotic_variance_xi.RData"))

plot_data_filtered <- plot_data[-c(683,689),]

plot_data_clean <- na.omit(plot_data_filtered)


```


```{r}
plot_asymptotic_variance <- ggplot(plot_data_clean, aes(x = x, y = y, color = alpha)) +
  geom_line(size = 1.2) +
  theme_minimal() +
    scale_colour_viridis_d(option = "plasma",
                           name = expression(~~~~alpha))+
  labs(
    x = TeX("$\\xi$"),
    y = "Variance"
  )+
  # scale_x_continuous(
  #   breaks = list_quantile,
  #   labels = p
  # ) +
  theme(legend.position =c(0.25,0.75),
        legend.title=element_text(size=26,face="bold"),
        legend.text =element_text(size=24))+
  theme(
    axis.title = element_text(size = 24),   
    axis.text = element_text(size = 18)
  )
plot_asymptotic_variance
```

```{r}
ggsave(plot = plot_asymptotic_variance,
       filename = paste0("C:/Users/huetn/Documents/github_repos/robustGEV/simulation/figures/asymptotic_variance_xi.png"),
       width = 1760 / 180,
       height = 1060 / 180,
       dpi = 180,
       units = "in")
```

