
R code for plot of the UK map

```{r}
#rm(list=ls())
library(sf)
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggrepel)
library(ggpubr)
```

```{r}
uk <- ne_countries(scale = "medium", country = "United Kingdom", returnclass = "sf")
```

```{r}
stations <- data.frame(
  id = c("10001", "50014", "69028", "71011"),
  river = c("Ythan River", "Yeo River",  "Mersey River", "Ribble River"),
  lat = c(57.35, 51.1,  53.4, 54.0),
  lon = c(-2.12, -4,  -2.17, -2.25),
  first_year = c(1939,1967,1955,1970),
  last_year = c(1984,2023,2023,2023),
  pilf_prop = c(0.04, 0.09, 0.07, 0.04),
  colors = c("#0d1687","#db5c68","#f48848","#f0f920")
)
```

```{r}
stations$legend_label <- paste0(
  stations$id, " : ", stations$river,
  " — ", stations$first_year, "-", stations$last_year,
  " — ", "PILFs: ", stations$pilf_prop
)

plt <- ggplot(data = uk) +
  geom_sf(fill = "antiquewhite") +
 geom_point(
  data = stations,
  aes(x = lon, y = lat, color = legend_label),
  size = 3
) +
scale_color_manual(values = stations$colors)+
  geom_text_repel(
    data = stations,
    aes(x = lon, y = lat, label = id),
    size = 4, nudge_y = 0, show.legend = FALSE
  ) +
  coord_sf(xlim = c(-8, 2), ylim = c(49.5, 59)) +
  labs(
    title = "",
    subtitle = "",
    x = "Longitude", y = "Latitude", color = ""
  ) +
  theme_minimal() +
  theme(legend.position = "right",
    #legend.position = "none",
      legend.key.height = unit(0.8, "cm"), 
    legend.text = element_text(size = 14),
      axis.title = element_text(size = 14),
      axis.text = element_text(size = 12)
    )

plt
```

```{r}
ggsave(plot = plt,
       filename = "C:/Users/huetn/Documents/github_repos/robustGEV/application/figures/map_uk.png",
       width = 1760 / 180,
       height = 1060 / 180,
       dpi = 180,
       units = "in")
```


