R code for asymptotic variance of MDPDE and MLE

```{r}
rm(list = ls())
library(latex2exp)
library(ggplot2)
library(MASS)

options(scipen = 999)

source("C:/Users/huetn/Documents/github_repos/robustGEV/functions/asymptotic_variance.R")
```

Plot asymptotic variances

Shape parameter

```{r}

alphas <- c(0, 0.1, 0.3, 0.5, 1)

mu <- 0
sigma <- 1

plot_data_xi <- data.frame()

for (alpha in alphas) {
  print(alpha)
  xi_min <- -(1 + alpha) / (2 + alpha)
  
  xi_vals <- seq(round(xi_min+0.01,2), 1, 0.01)
  
  y <- sapply(xi_vals, function(xi)
    {
    print(xi)
    asymptotic_variance_mdpde_componentwise(mu = mu,
                                          sigma = sigma,
                                          xi = xi,
                                          alpha = alpha,
                                          coord=c(3,3))
    }
    )
  df <- data.frame(x = xi_vals, y = y, alpha = as.factor(alpha))
  plot_data_xi <- rbind(plot_data_xi, df)
}

```

```{r}
#save(plot_data_xi,file=paste0("C:/Users/huetn/Documents/github_repos/robustGEV/simulation/new_generated_datasets/df_asymptotic_variance_xi.RData"))

load(file=paste0("C:/Users/huetn/Documents/github_repos/robustGEV/simulation/new_generated_datasets/df_asymptotic_variance_xi.RData"))

plot_data_xi_filtered <- plot_data[-c(683,689),]

plot_data_xi_clean <- na.omit(plot_data_xi_filtered)
```

```{r}
plot_asymptotic_variance_xi <- ggplot(plot_data_xi_clean, aes(x = x, y = y, color = alpha)) +
  geom_line(size = 1.2) +
  theme_minimal() +
    scale_color_manual(
      values = c("0" = "#1b1a81",
                 "0.1" = "#7c2f9f",
                 "0.3" = "#c54ba0",
                 "0.5" = "#f3904e",
                 "1" = "#d1d84d"),
      name = expression(~~~~alpha))+
  labs(
    x = TeX("$\\xi$"),
    y = "Asympt. Var. (shape)"
  )+
  # scale_x_continuous(
  #   breaks = list_quantile,
  #   labels = p
  # ) +
  theme(legend.position =c(0.25,0.75),
        legend.title=element_text(size=26,face="bold"),
        legend.text =element_text(size=24))+
  theme(
    axis.title = element_text(size = 24),   
    axis.text = element_text(size = 18)
  )
plot_asymptotic_variance_xi
```

```{r}
ggsave(plot = plot_asymptotic_variance_xi,
       filename = paste0("C:/Users/huetn/Documents/github_repos/robustGEV/simulation/new_figures/asymptotic_variance_xi.png"),
       width = 1760 / 180,
       height = 1060 / 180,
       dpi = 180,
       units = "in")
```

Scale parameter

```{r}

alphas <- c(0, 0.1, 0.3, 0.5, 1)

mu <- 0
sigma <- 1

plot_data_scale <- data.frame()

for (alpha in alphas) {
  print(alpha)
  xi_min <- -(1 + alpha) / (2 + alpha)
  
  xi_vals <- seq(round(xi_min+0.01,2), 1, 0.01)
  
  y <- sapply(xi_vals, function(xi)
    {
    print(xi)
    asymptotic_variance_mdpde_componentwise(mu = mu,
                                          sigma = sigma,
                                          xi = xi,
                                          alpha = alpha,
                                          coord=c(2,2))
    }
    )
  df <- data.frame(x = xi_vals, y = y, alpha = as.factor(alpha))
  plot_data_scale <- rbind(plot_data_scale, df)
}

```

```{r}
#save(plot_data,file=paste0("C:/Users/huetn/Documents/github_repos/robustGEV/simulation/new_generated_datasets/df_asymptotic_variance_sigma.RData"))

load(file="C:/Users/huetn/Documents/github_repos/robustGEV/simulation/new_generated_datasets/df_asymptotic_variance_sigma.RData")

plot_data_scale_filtered <- plot_data_scale[-c(683,689),]

plot_data_scale_clean <- na.omit(plot_data_scale_filtered)
```

```{r}
plot_asymptotic_variance_sigma <- ggplot(plot_data_scale_clean, aes(x = x, y = y, color = alpha)) +
  geom_line(size = 1.2) +
  theme_minimal() +
    scale_color_manual(
      values = c("0" = "#1b1a81",
                 "0.1" = "#7c2f9f",
                 "0.3" = "#c54ba0",
                 "0.5" = "#f3904e",
                 "1" = "#d1d84d"),
      name = expression(~~~~alpha))+
  labs(
    x = TeX("$\\xi$"),
    y = "Asympt. Var. (scale)"
  )+
  # scale_x_continuous(
  #   breaks = list_quantile,
  #   labels = p
  # ) +
  theme(legend.position ="none",
        legend.title=element_text(size=26,face="bold"),
        legend.text =element_text(size=24))+
  theme(
    axis.title = element_text(size = 24),   
    axis.text = element_text(size = 18)
  )
plot_asymptotic_variance_sigma
```

```{r}
ggsave(plot = plot_asymptotic_variance_sigma,
       filename = paste0("C:/Users/huetn/Documents/github_repos/robustGEV/simulation/new_figures/asymptotic_variance_sigma.png"),
       width = 1760 / 180,
       height = 1060 / 180,
       dpi = 180,
       units = "in")
```

Location parameter

```{r}

alphas <- c(0, 0.1, 0.3, 0.5, 1)

mu <- 0
sigma <- 1

plot_data_loc <- data.frame()

for (alpha in alphas) {
  print(alpha)
  xi_min <- -(1 + alpha) / (2 + alpha)
  
  xi_vals <- seq(round(xi_min+0.01,2), 1, 0.01)
  
  y <- sapply(xi_vals, function(xi)
    {
    print(xi)
    asymptotic_variance_mdpde_componentwise(mu = mu,
                                          sigma = sigma,
                                          xi = xi,
                                          alpha = alpha,
                                          coord=c(1,1))
    }
    )
  df <- data.frame(x = xi_vals, y = y, alpha = as.factor(alpha))
  plot_data_loc <- rbind(plot_data_loc, df)
}

```

```{r}
#save(plot_data,file=paste0("C:/Users/huetn/Documents/github_repos/robustGEV/simulation/new_generated_datasets/df_asymptotic_variance_sigma.RData"))

load(file="C:/Users/huetn/Documents/github_repos/robustGEV/simulation/new_generated_datasets/df_asymptotic_variance_mu.RData")

plot_data_loc_filtered <- plot_data_loc[-c(683,689),]

plot_data_loc_clean <- na.omit(plot_data_loc_filtered)
```

```{r}
plot_asymptotic_variance_mu <- ggplot(plot_data_loc_clean, aes(x = x, y = y, color = alpha)) +
  geom_line(size = 1.2) +
  theme_minimal() +
    scale_color_manual(
      values = c("0" = "#1b1a81",
                 "0.1" = "#7c2f9f",
                 "0.3" = "#c54ba0",
                 "0.5" = "#f3904e",
                 "1" = "#d1d84d"),
      name = expression(~~~~alpha))+
  labs(
    x = TeX("$\\xi$"),
    y = "Asympt. Var. (location)"
  )+
  # scale_x_continuous(
  #   breaks = list_quantile,
  #   labels = p
  # ) +
  theme(legend.position ="none",
        legend.title=element_text(size=26,face="bold"),
        legend.text =element_text(size=24))+
  theme(
    axis.title = element_text(size = 24),   
    axis.text = element_text(size = 18)
  )
plot_asymptotic_variance_mu
```

```{r}
ggsave(plot = plot_asymptotic_variance_mu,
       filename = paste0("C:/Users/huetn/Documents/github_repos/robustGEV/simulation/new_figures/asymptotic_variance_mu.png"),
       width = 1760 / 180,
       height = 1060 / 180,
       dpi = 180,
       units = "in")
```